USE Musica;

CREATE TABLE Artistas
(
IdArtista INT PRIMARY KEY IDENTITY
,Nome VARCHAR(200) NOT NULL
);
CREATE TABLE Estilos
(
IdEstilo INT PRIMARY KEY IDENTITY
,Nome VARCHAR(200)
);
CREATE TABLE Usuarios
(
IdUsuario INT PRIMARY KEY IDENTITY
,Nome VARCHAR(200) NOT NULL
,Email VARCHAR(200)NOT NULL
,Senha VARCHAR (200) NOT NULL
,Permissao VARCHAR(200)
);

CREATE TABLE Albuns
(
IdAlbum INT PRIMARY KEY IDENTITY
,IdArtista INT FOREIGN KEY REFERENCES Artistas
,Titulo VARCHAR(200)
,DataLancamento VARCHAR(200)
,Localizacao VARCHAR(200)
,QtdMinutos VARCHAR(200)
,Ativo VARCHAR(200)
);

CREATE TABLE AlbunsEstilo
(
IdAlbum INT FOREIGN KEY REFERENCES Albuns
,IdEstilo INT FOREIGN KEY REFERENCEs Estilos
);