USE PetShop;

CREATE TABLE Clinicas
(
IdClinica INT PRIMARY KEY IDENTITY
,RazaoSocial VARCHAR(200) NOT NULL
,CNPJ VARCHAR(200) NOT NULL
,Endereco VARCHAR(200) NOT NULL
,Nome VARCHAR(200) NOT NULL
);
CREATE TABLE Veterinarios
(
IdVeterinario INT PRIMARY KEY IDENTITY
,IdClinica INT FOREIGN KEY REFERENCES Clinicas
,Nome VARCHAR(200)
,CRMV VARCHAR (200) NOT NULL
);
CREATE TABLE TiposPets
(
IdTipo INT PRIMARY KEY IDENTITY
,Descricao VARCHAR(200)
);
CREATE TABLE Racas
(
IdRacas INT PRIMARY KEY IDENTITY
,IdTipo INT FOREIGN KEY REFERENCES TiposPets
,Descricao VARCHAR(200)
);
CREATE TABLE Donos
(
IdDono INT PRIMARY KEY IDENTITY
,Nome VARCHAR(200)

);
CREATE TABLE Pets
(
IdPet INT PRIMARY KEY IDENTITY
,IdDono INT FOREIGN KEY REFERENCES Donos
,IdRacas INT FOREIGN KEY REFERENCES Racas
,Nome VARCHAR(200)
,DataNascimento VARCHAR(200)
);
CREATE TABLE Atendimentos
(
IdAtendimento INT PRIMARY KEY IDENTITY
,IdPet INT FOREIGN KEY REFERENCES Pets
,IdVeterinario INT FOREIGN KEY REFERENCES Veterinarios
,Descricao VARCHAR(200)
,DataConsulta VARCHAR(200)
);